### ISSUE TITLE
Error "Not a valid IA5String string." but it's valid

### ISSUE THREAD

**Issue by LufoX11** [sop/asn1#17]
Hi! I'm doing the following:
```php
// $file => "./01.crt" => https://www.acraiz.gob.ar/Content/Archivos/certificados/licenciados_acraiz2016/01.crt
$pem = Sop\CryptoEncoding\PEM::fromFile($file);
$cert = Sop\X509\Certificate\Certificate::fromPEM($pem);
```
And for that particular PEM file I'm getting:
```bash
PHP Fatal error:  Uncaught InvalidArgumentException: Not a valid IA5String string. in /.../vendor/sop/asn1/lib/ASN1/Type/BaseString.php:31
Stack trace:
#0 /.../vendor/sop/asn1/lib/ASN1/Type/Primitive/IA5String.php(25): Sop\ASN1\Type\BaseString->__construct()
#1 /.../vendor/sop/asn1/lib/ASN1/Type/PrimitiveString.php(48): Sop\ASN1\Type\Primitive\IA5String->__construct()
#2 /.../vendor/sop/asn1/lib/ASN1/Element.php(211): Sop\ASN1\Type\PrimitiveString::_decodeFromDER()
#3 /.../vendor/sop/asn1/lib/ASN1/Type/Structure.php(372): Sop\ASN1\Element::fromDER()
#4 /.../vendor/sop/asn1/lib/ASN1/Type/Structure.php(348): Sop\ASN1\Type\Structure::_decodeDefiniteLength()
#5 /.../vendor/sop/asn1/lib/ASN1/Element.php(211): Sop\ASN1\Type\Structure::_decodeFromDER()
#6 /var/www/l in /.../vendor/sop/asn1/lib/ASN1/Type/PrimitiveString.php on line 50
```
It works if I override this validation in `vendor/sop/asn1/lib/ASN1/Type/Primitive/IA5String.php`:
```php
 28     /**
 29      * {@inheritdoc}
 30      */
 31     protected function _validateString(string $string): bool
 32     {                                                                                                                                                                       
 33         return true;
 34         //return 0 == preg_match('/[^\x01-\x7f]/', $string);
 35     }   
 36 }  
```
Am I doing something wrong, or is there some workaround to get over this?
Please help, I'm kind of desperate since I spent an entire day and I can't solve it. Thank you in advance!

**Comment by sop** [comment]
Hi!

Thanks for the report. Looks like ASCII nul's _(\0)_ should be allowed in IA5String encoding. There's a URL field in your certificate that contains a null character. Whether or not that is intended, i don't know.
Anyway, nul's were previously excluded from the allowed characters (\x01-\x7f range). I've fixed this to contain all lower ASCII characters.
New 4.1.1 tag has been pushed to packagist and should be available for you via `composer update`!

**Comment by LufoX11** [comment]
Oh man you are the best! I really appreciate it, thank you very much!!
